function [LL, UR, LR, UL] = stquantaildep_AC(u, delta, OmegaBar, nu)
% stquantaildep_AC: calculate upper & lower dependence of A&C's skew T copula
% Azzalini, A., & Capitanio, A. (2003). Distributions generated by perturbation of symmetry with emphasis on a multivariate skew t
% -distribution. Journal of the Royal Statistical Society: Series B (Statistical Methodology), 65(2), 367–389. doi:10.1111/1467-9868.00391
% 
% INPUTS
% delta1, delta2: constrained skewness parameter of x1, x2
% omega: correlation of data [x1, x2]
% nu: degree of freedom
% 
% OUTPUTS
% LL:   Lower Left (Lower Tail - major diagonal)
% UR:   Upper Right (Upper Tail - major diagonal)
% LR:   Lower Right (Lower Tail - minor diagonal)
% UL:   Upper Left (Upper Tail - minor diagonal)
% (x1, x2): (U, V) < (u, u)
% (y1, y2): (U, V) < (1-u, 1-u)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 28/06/2021

if nu > 100
    nu = 100;
end
x1 = stinv(u, delta(1), nu); % skew T inverse: u --> x
if abs(delta(2) - delta(1)) < 1e-5
    x2 = x1;
else
    x2 = stinv(u, delta(2), nu);
end

y1 = stinv(1-u, delta(1), nu); % skew T inverse: u --> x
if abs(delta(2) - delta(1)) < 1e-5
    y2 = y1;
else
    y2 = stinv(1-u, delta(2), nu);
end

XLL = [x1, x2];
CopulaLL = mvstcdf(XLL, delta, OmegaBar, nu);
LL = CopulaLL ./ u;

XUR = [y1, y2];
CopulaUR = mvstcdf(XUR, delta, OmegaBar, nu);
UR = (CopulaUR+2*u-1)./u;

XLR = [y1, x2];
CopulaLR = mvstcdf(XLR, delta, OmegaBar, nu);
LR = 1 - CopulaLR./u;

XUL = [x1, y2];
CopulaUL = mvstcdf(XUL, delta, OmegaBar, nu);
UL = 1 - CopulaUL./u;

end